//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Move
    {
        public int MoveId { get; set; }
        public System.DateTime RecordTime { get; set; }
        public int posX { get; set; }
        public int posY { get; set; }
        public int pathIndex { get; set; }
        public string User_Email { get; set; }
        public Nullable<int> Game_GameId { get; set; }
    
        public virtual Game Game { get; set; }
        public virtual User User { get; set; }
    }
}
