//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckersService
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int Id { get; set; }
        public int Row { get; set; }
        public int Column { get; set; }
        public Nullable<int> EatPointId { get; set; }
        public Nullable<int> MovePointId { get; set; }
    
        public virtual Move PointToEat { get; set; }
        public virtual Move PointToMove { get; set; }
    }
}
